name: 'rblxsync'
description: 'Declaratively manage Roblox experience metadata via Open Cloud API'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  api_key:
    description: 'Roblox Open Cloud API Key'
    required: true
  command:
    description: 'Command to run: run, publish, validate, or export'
    required: false
    default: 'run'
  config:
    description: 'Path to rblxsync.yml config file'
    required: false
    default: 'rblxsync.yml'
  args:
    description: 'Additional arguments (e.g., --dry-run for run command)'
    required: false
    default: ''
  roblox_cookie:
    description: 'Roblox .ROBLOSECURITY cookie (required for universe settings)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout rblxsync
      uses: actions/checkout@v4
      with:
        repository: dig1t/rblxsync
        path: .rblxsync-action

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          .rblxsync-action/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('.rblxsync-action/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build rblxsync
      shell: bash
      working-directory: .rblxsync-action
      run: cargo build --release

    - name: Run rblxsync
      shell: bash
      env:
        ROBLOX_API_KEY: ${{ inputs.api_key }}
        ROBLOX_COOKIE: ${{ inputs.roblox_cookie }}
      run: |
        .rblxsync-action/target/release/rblxsync ${{ inputs.command }} --config ${{ inputs.config }} ${{ inputs.args }}

